version: '3.8'

services:
  virtome:
    image: postgres:14-alpine
    container_name: vir-tome
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: virtome_password
      POSTGRES_DB: virtome_dev_db
      POSTGRES_USER: virtome_user
      POSTGRES_PASSWORD: virtome_password
    ports:
      - "5438:5432"
    volumes:
      - virtome_pg_data:/var/lib/pg
  # otra db de test
  virtome_test:
    image: postgres:14-alpine
    container_name: vir-tome-test
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: test
      POSTGRES_DB: virtome_test_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5439:5432"
    volumes:
      - virtome_pg_test_data:/var/lib/pg

volumes:
  virtome_pg_data:
  virtome_pg_test_data: