export const DEMO_BOOKS_DATA = [
	{
		title: 'Martín Fierro (Adaptación Infantil)',
		author: 'José Hernández',
		publicationYear: 2020,
		availableQuantity: 8,
		category: 'Literatura Argentina',
		publisher: 'Editorial Santillana',
		isbn: '978-950-46-1234-5',
	},
	{
		title: 'La Vuelta de Rocha',
		author: 'María Elena Walsh',
		publicationYear: 2019,
		availableQuantity: 12,
		category: 'Literatura Infantil',
		publisher: 'Alfaguara',
		isbn: '978-987-04-5678-9',
	},
	{
		title: 'Billiken - Ciencias Naturales 4°',
		author: 'Equipo Billiken',
		publicationYear: 2023,
		availableQuantity: 15,
		category: 'Ciencias Naturales',
		publisher: 'Editorial Atlántida',
		isbn: '978-987-07-1234-5',
	},
	{
		title: 'Manual Santillana Matemática 4°',
		author: 'Equipo Santillana',
		publicationYear: 2024,
		availableQuantity: 20,
		category: 'Matemáticas',
		publisher: 'Editorial Santillana',
		isbn: '978-950-46-7890-1',
	},
	{
		title: 'Cuentos de la Patagonia',
		author: 'Varios Autores',
		publicationYear: 2021,
		availableQuantity: 6,
		category: 'Cuentos Regionales',
		publisher: 'Sudamericana',
		isbn: '978-950-07-2468-0',
	},
];

export const DEMO_USERS_DATA = [
	{
		name: 'María José',
		surname: 'González',
		email: 'directora@demo.edu.ar',
		role: 'Administrador',
		dni: '12345678',
	},
	{
		name: 'Carlos Alberto',
		surname: 'Fernández',
		email: 'biblioteca@demo.edu.ar',
		role: 'Bibliotecario',
		dni: '23456789',
	},
	{
		name: 'Ana Laura',
		surname: 'Martínez',
		email: 'profesora.ana@demo.edu.ar',
		role: 'Profesor',
		dni: '34567890',
	},
	{
		name: 'Roberto',
		surname: 'Silva',
		email: 'profesor.roberto@demo.edu.ar',
		role: 'Profesor',
		dni: '45678901',
	},
	{
		name: 'Valentina',
		surname: 'López',
		email: 'vlopez@demo.edu.ar',
		role: 'Estudiante',
		dni: '56789012',
	},
];
