export const argPublishers = [
	'17 grises',
	'7 Sellos Editorial Cooperativa',
	'A&L Editores',
	'A-Z Editora SA',
	'A.C.E.S.',
	'ABRE, El Gato y La Caja',
	'Abaco',
	'Abarcar Ediciones',
	'Abran Cancha, Ediciones',
	'Acercandonos Editorial',
	'Ad-Hoc',
	'Adriana Hidalgo',
	'Advocatus',
	'Agape Libros',
	'Aique Grupo Editor',
	'Ajdut Israel',
	'Akadia',
	'Al Margen',
	'Alarco, Ediciones',
	'Albatros',
	'Albrematica, Editorial',
	'Alción Editora',
	'Alfagrama',
	'Alfaomega Grupo Editor Argentino',
	'Alianza',
	'Alienta Editorial',
	'Aljaba Producciones',
	'Alma Lepik',
	'Alsina, Libreria Y Editorial',
	'Alveroni Ediciones',
	'Amauta Argentina Srl',
	'America Libros',
	'Ami Books',
	'Amorrortu',
	'Anejo',
	'Antidoto',
	'Antropofagia',
	'Antroposofica, Editorial',
	'Apostrofe Ediciones',
	'AqL',
	'Arcadia Argentina Ediciones',
	'Argenta Sarlep',
	'Argentores',
	'Argonauta, Editorial',
	'Ariel',
	'Ariza Julia',
	'Arte A Babor',
	'Artenautas',
	'Arterapia',
	'Artes Gráficas Crivell',
	'As. Escuela Cientifica Basilio',
	'As.A.G.A.',
	'Asoc. Budista - Ibps Argentina',
	'Asoc. Civil Estudio De Falun Dafa',
	'Asoc. Colegio Adventista Del Plata',
	'Astrea, Editorial',
	'Atlante',
	'Atuel, Editorial',
	'Aurelia Rivera',
	'Autoria Consultora',
	'Azul Ediciones',
	'Baez Ediciones',
	'Balletin Dance',
	'Bambali Ediciones I Y M.V. Sloss',
	'Barcelbaires',
	'Barry, Editorial',
	'Bartolome Gerardo Miguel',
	'Beatriz Viterbo Editora',
	'Beeme',
	'Betina',
	'Biblos, Editorial',
	'Bienes Raices Ediciones',
	'Biribetto, Editorial',
	'Birkat Elohym',
	'Blatt & Rios',
	'Bonsai, Editorial',
	'Bonum',
	'Bonvivant Editions',
	'Book4Pocket',
	'Bookfactory.Com Srl',
	'Books Services Company S.R.L.',
	'Borde perdido editora',
	'Botella al Mar',
	'Boutique de Ideas',
	'Breitfeld Alfredo',
	'Brihet e Hijos SA',
	'Brujas, Editorial',
	'Buena Prensa',
	'Buena Vista Editores',
	'C.C.C. Editorial Educando',
	'Cspide Libros',
	'Caballo Negro Editora',
	'Cactus',
	'Caja Negra Editora',
	'Caleuche',
	'Calibroscopio',
	'Camara De Lib., Pap. Y Afines',
	'Camino al Corazón',
	'Capin, Editorial',
	'Carlos Lungarini',
	'Carpetas De Derecho S.A.',
	'Cartografías Ediciones',
	'Casa 13 ediciones',
	'Casa Nazarena de Publicaciones',
	'Casa de las Tejas',
	'Casa del Puente Ediciones',
	'Casassa Y Lorenzo Libreros Sa',
	'Castellano Libros',
	'Castinver Sa',
	'Catapulta',
	'Cathedra Juridica',
	'Cauquen Editora',
	'Celtia',
	'Cen Ediciones',
	'Cengage Learning Argentina',
	'Centella Ediciones',
	'Centro Editor Contemporaneo',
	'Centro Latinoamericano De Comercio S.A',
	'Centro de Estudios Avanzado, Editorial de la Facultad de Arquitectura, Urbanismo y Diseño,',
	'Centro de Estudios Avanzados',
	'Centro de Publicaciones Educativas y Material Didáctico - NOVEDUC',
	'Cepa - Ciudad Argentina',
	'Certeza',
	'Cia. Naviera Ilimitada Editores',
	'Ciencia Y Tecnica Libros',
	'Circulo De Lectores',
	'Circulo Latino Austral',
	'Ciudad Gótica',
	'Ciudad Nueva',
	'Clacso',
	'Claretiana',
	'Close Up',
	'Club Burton',
	'Clyna',
	'Colegio de Traductores Públicos de la  Ciudad Autónoma de Buenos Aires',
	'Colihue',
	'Colision Libros',
	'Como Gog y Magog Ediciones',
	'Comunic-Arte',
	'Condorhuasi',
	'Confederacion Espiritista Argentina',
	'Conferencia Episcopal Argentina',
	'Consejo Interuniversitario Nacional',
	'Consejo Profesional de Ciencias Economicas',
	'Contamusa',
	'Contexto',
	'Continente Ediciones',
	'Cooperativa Comunidad',
	'Corpus Libros',
	'Corpus Libros Mdicos y Cientficos',
	'Corregidor',
	'Cp 67, Libreria Tecnica',
	'Creadores Argentinos',
	'Creavit',
	'Crecer  Creando',
	'Crossover Comics Store',
	'Cuadernos del Duende',
	'Cuenta Conmigo Ediciones',
	'Cypres',
	'D & D, Ediciones',
	'DFL Ediciones',
	'De Dios Editores',
	'De La Flor',
	'De Las Tres Lagunas',
	'De Los Cuatro Vientos',
	'De Mente, Ediciones',
	'De la Campana',
	'De la Talita Dorada',
	'Del Alma Editores',
	'Del Aula Taller, Ediciones',
	'Del Cami Latina',
	'Del Clé',
	'Del Cronopio Azul',
	'Del Dragon, Ediciones',
	'Del Futuro, Distribuciones',
	'Del Hospital Ediciones',
	'Del Jurista, Libreria',
	'Del Nuevo Extremo',
	'Del Sol',
	'Delta Editora',
	'Desde La Gente',
	'Deva',
	'Di Lalla Ediciones',
	'Dial Book',
	'Diamond Books',
	'Diaz Horacio Miguel',
	'Diblasa Srl',
	'Dirac Dist. S.A',
	'Distal',
	'Distribuidora Alberto Luongo S.A.',
	'Distribuidora Librum',
	'Docencia S.A.',
	'Documenta',
	'Domb Barbara Y Domb Ezequiel Sh',
	'Don Bosco, Ediciones',
	'Dosyuna Ediciones Argentinas',
	'Dryl Sa',
	'Dunken, Editorial',
	'Dínamo Poético',
	'EDIUNC',
	'EDUCC -Editorial Universidad Católica de Córdoba-',
	'EDUCO - Editorial Universitaria del Comahue',
	'EDULP',
	'EDUNAM - Editorial Universitaria de la Universidad Nacional de Misiones',
	'EDUNER',
	'EDUNTREF',
	'EFU, Editorial de UNSJ',
	'EUCASA, Editorial de la Universidad Católica de Salta',
	'EUDEM',
	'EUNSA, Editorial de la UNS',
	'EVIA Ediciones',
	'Ed. De La Un. Del Aconcagua',
	'EdUNLa',
	'EdUnlu',
	'EdUtecNe',
	'Edhasa',
	'EdiBer - Editorial Municipal de Berazategui',
	'Ediar',
	'Ediba',
	'Ediciones Akal Suc Argentina',
	'Ediciones Al Sur Srl',
	'Ediciones Aldea Hippie',
	'Ediciones Ampersand',
	'Ediciones Argentinidad',
	'Ediciones Biebel',
	'Ediciones Cooperativas',
	'Ediciones De La Terraza',
	'Ediciones Del Camino',
	'Ediciones Del Dock',
	'Ediciones Del Mar',
	'Ediciones Del Pulpo Negro',
	'Ediciones Didot',
	'Ediciones En Danza',
	'Ediciones Enepe',
	'Ediciones Fabro',
	'Ediciones GCC',
	'Ediciones Godot',
	'Ediciones Herramienta',
	'Ediciones Inta - Centro Regional la Pampa-San Luis',
	'Ediciones Ips',
	'Ediciones Joselin',
	'Ediciones Lariviere',
	'Ediciones Lea',
	'Ediciones Lerner',
	'Ediciones Luxemburg',
	'Ediciones Pido la Palabra',
	'Ediciones Rap S.A.',
	'Ediciones Simurg',
	'Ediciones Sm Sa',
	'Ediciones Triunfo (Fundación Antares)',
	'Ediciones UNL',
	'Ediciones Voces del Sur',
	'Ediciones Winogrand',
	'Ediciones del Boulevard',
	'Ediciones del CCC Centro Cultural de la Cooperación Floreal Gorini; Instituto Movilizador de Fondos Cooperativos; Desde la Gente,',
	'Ediciones del Corredor Austral',
	'Ediciones del Naranjo',
	'Ediciones del Signo',
	'Ediciones del Sur',
	'Edicol',
	'Edifel Libros',
	'Editora Cultural Tierra del Fuego',
	'Editores Del Sur',
	'Editorial Almaluz',
	'Editorial Asuimagen',
	'Editorial Atlántida SA',
	'Editorial Biotecnologica',
	'Editorial Cafe De Las Ciudades',
	'Editorial Cientifica Universitaria',
	'Editorial Croquis S.R.L.',
	'Editorial De La Palabra De Dios',
	'Editorial Deaca',
	'Editorial Del Arbol',
	'Editorial Diamante',
	'Editorial Didascalia',
	'Editorial Dorothea',
	'Editorial El Abuelo Pablo',
	'Editorial El Ateneo',
	'Editorial Entropia',
	'Editorial Estrada S.A.',
	'Editorial Estudio',
	'Editorial Ferias Y Congresos',
	'Editorial Fundacion La Hendija',
	'Editorial Fundación H. A. Barceló',
	'Editorial Jus Baires',
	'Editorial Kuruf',
	'Editorial Letranomada',
	'Editorial Logos',
	'Editorial Los Andes',
	'Editorial Milor',
	'Editorial Médica AWWE',
	'Editorial Océano Argentina SA',
	'Editorial Patagónia Activa',
	'Editorial Punto De Encuentro',
	'Editorial Quadrata',
	'Editorial Reconquista',
	'Editorial Saban',
	'Editorial San Pablo',
	'Editorial Santa Maria',
	'Editorial Sudestada',
	'Editorial Tirnan',
	'Editorial UNICEN',
	'Editorial Universitaria Rioplatense',
	'Editorial de Entre Rios',
	'Editorial de la UNT',
	'Editorial de la Universidad Nacional Del Sur',
	'Editorial de la Universidad Nacional de Formosa',
	'Editorial de la Universidad Nacional del Nordeste EUDENE',
	'Editorial de la Universidad de Quilmes',
	'Eduvim',
	'El Aleph',
	'El Buen Libro',
	'El Cazador',
	'El Colectivo',
	'El Cuenco De Plata',
	'El Derecho, Universitas',
	'El Emprio Libros',
	'El Escriba',
	'El Hilo De Ariadna Srl',
	'El Mundo Magico De Las Letras',
	'El Servicio Postal',
	'El Suri Porfiado Ediciones',
	'El Tabaquillo',
	'El Zahir Editora',
	'Elektra Comics',
	'Elemento',
	'Elguero Ediciones',
	'Entelequia, Libreria',
	'Envaplast S.R.L.',
	'Errepar',
	'Esfera Grafica Srl',
	'Espacio Hudson',
	'Espacio, Editorial',
	'Espartaco Córdoba',
	'Estacion Mandioca',
	'Estari Libros',
	'Eterna Cadencia S.R.L.',
	'Eudeba',
	'Eudecor',
	'Euros',
	'Ex Libris',
	'Extremo Sur',
	'Fabián J. Di Plácido Editor',
	'Fabrica De Fotolibros.Com',
	'Ferreyra Editor',
	'Filatelia Jalil',
	'Final Abierto',
	'Fink Nadia Paola',
	'Fondo De Cultura Económica',
	'Fondo Editorial Ministerio de Cultura y Turismo',
	'Fondo Editorial Provincial',
	'Fondo Editorial Rionegrino',
	'Frigga Editora',
	'Fund. Medife',
	'Fund.Arg.Educ.Y Accion Comunit',
	'Fundacin Cristiana De Evangeliz.',
	'Fundacion Arte Ba',
	'Fundacion Ciccus',
	'Fundacion Edelvives',
	'Fundacion Foro Del Sur',
	'Fundacion Foro Nueva Sociedad',
	'Fundacion Friedrich Naumann',
	'Fundacion Hastinapura',
	'Fundacion Jean Piaget',
	'Fundacion Pan Klub',
	'Fundacion Proa',
	'Fundacion Rey De Reyes',
	'Fundacion U.C.A.',
	'Fundación Hospital De Pediatria',
	'Funlar',
	'Gabriel Badaraco',
	'Galerna',
	'Garcia Alonso',
	'Garcia Cambeiro',
	'Garcia Griselda',
	'Gerbera Ediciones',
	'Giscafre Marcela Beatriz',
	'Gladius',
	'Golden Company',
	'Gorla',
	'Gourmand Place',
	'Gourmet Musical Ediciones',
	'Gradifco',
	'Gram, Editora',
	'Grama Ediciones',
	'Gran Aldea',
	'Granica',
	'Grito Sagrado',
	'Grupal',
	'Grupo Artemisa',
	'Grupo Clasa',
	'Grupo Dinámica',
	'Grupo Editor Latinoamericano',
	'Grupo Logos',
	'Grupo Proactivo S.A.',
	'Grupo Union',
	'Guadalupe, Editorial',
	'Guardacostas',
	'Gustavo Multedo',
	'Hammurabi',
	'Hekht Libros',
	'Heliasta',
	'Hemisferio Derecho',
	'Hemisferio Sur',
	'Hernandez, Libreria',
	'Hipocratico Sa',
	'Hola Chicos',
	'Holograma',
	'Homosapiens, Ediciones',
	'Hub Editorial',
	'Huellas - Ikono',
	'Huesos de Jibia',
	'I+P Editorial',
	'Iamique',
	'Idiomagic',
	'Imaginador',
	'Imaginate Editorial',
	'Imago Mundi',
	'Impresiones Buenos Aires Editorial',
	'Impresos S.A.',
	'Induvio Profesional',
	'Infantil.Com',
	'Infinito',
	'Insignia',
	'Inst. De Publicaciones Navales',
	'Inst. Salesiana Ntra Sra De Lujan',
	'Instituto Americano',
	'Instituto Nacional de Estadística y Censos - INDEC',
	'Intercoop Editora Coop. Lda.',
	'Intermedica',
	'Interzona Editora',
	'Iriarte Pilar Margarita',
	'Irojo Editores',
	'Jarmat',
	'Jerez Editores',
	'Journal',
	'Joyce Proust',
	'Juridicas',
	'Juris, Editorial',
	'Kairos, Ediciones',
	'Kapelusz Editora S.A.',
	'Katz',
	'Kehot, Editorial',
	'Kel',
	'Kexploten Lunas',
	'Kier, Editorial',
	'Konrad Adenauer Stiftung',
	'La Bestia Equilatera Srl',
	'La Biblioteca De Sofia En Portuguez',
	'La Bisagra Editorial',
	'La Bohemia, Editorial',
	'La Botica',
	'La Brujita De Papel',
	'La Buena Semilla',
	'La Central Editorial',
	'La Comuna Ediciones',
	'La Coop',
	'La Editorial Comun',
	'La Esquina de los Vientos',
	'La Ley',
	'La Luna Qué',
	'La Marca',
	'La Nave De Los Locos',
	'La Pgina',
	'La Paragrafica',
	'La Periferica Distribuidora',
	'La Revisteria Comics',
	'La Rocca',
	'La Vanguardia Editora',
	'Laborde Libros Editor',
	'Lago',
	'Lajouane S.A.',
	'Landeira',
	'Ledargsa SA',
	'Lenguaje Claro Editora',
	'Letemendia Casa Editora',
	'Letra Impresa Grupo Editor',
	'Letra Viva',
	'Letras Del Sur',
	'Letras Nuevas',
	'Leviatan',
	'Libraria',
	'Libreria Aquilanti',
	'Libreria De Mujeres Editoras',
	'Libreria Mucho Gusto',
	'Libreria Norte Sa',
	'Libreria Raices (Tomas Catari)',
	'Libreria Rayuela',
	'Librerias Libertador',
	'Librería de la Paz',
	'Libros Argentinos',
	'Libros Condor',
	'Libros De La Araucaria',
	'Libros Del Zorro Rojo',
	'Libros Del Zorzal',
	'Lillo Cares Ruben Walter',
	'Limonero Textos Srl',
	'Linio Argentina Srl',
	'Llanto de Mudo',
	'Longseller',
	'Lopez Carlos',
	'Los Libros Mas Pequeños Del Mundo',
	'Los Ríos Editorial',
	'Losada, Editorial',
	'Lowing Produciones Sa',
	'Lucrecia, Ediciones',
	'Ludico Ediciones',
	'Lugar, Editorial',
	'Lumen, Lumen Hvmanitas, Magisterio del Ro de la Plata',
	'Lumiere',
	'Luminias Srl',
	'M & A',
	'M. Laffitte Ediciones',
	'Mdica Panamericana',
	'Macmillan Publishers S.A.',
	'Magnaverum',
	'Maipue, Editorial',
	'Maizal Ediciones',
	'Make A Book',
	'Malas Palabras Buks',
	'Malba',
	'Manantial, Ediciones',
	'Mansalva',
	'Marcial Pons Argentina',
	'Mardulce',
	'Marea',
	'Margen Izquierdo',
	'Martinez Irma Angelica',
	'Mc Graw Hill',
	'Mediterránea',
	'Mio Y Davila',
	'Mil Botellas Editorial',
	'Mil, Editorial (Amia)',
	'Milena Caserola',
	'Misiones Franciscanas Conventuales',
	'Modesto Rimba',
	'Moglia',
	'Monoblock',
	'Mujer Integra Sa',
	'Mundo Gráfico Salta Editorial',
	'My Special Book',
	'Mylibro',
	'Narvaja Editor',
	'Nativa Libros Srl',
	'Nazhira, Palabras Animadas',
	'Negro Absoluto S.A.',
	'Nelida Bonaldi',
	'Newgate',
	'Nio Editor',
	'Nicolas Von Der Pahlen',
	'Nova Tesis Editorial Jurídica',
	'Novak Diego Daniel',
	'Novak Mario Osvaldo',
	'Nuestra America',
	'Nueva Editorial Universitaria - U.N.S.L',
	'Nueva Libreria',
	'Nueva Vision',
	'Nuevos Tiempos',
	'Numeral',
	'Ojoreja',
	'Olmo Ediciones',
	'Orientación Gráfica Editora',
	'Orsai Bar',
	'Osmar Buyatti',
	'Ovni Press',
	'Oxford University',
	'Paisanita Editora',
	'Paprika',
	'Paradigma Libros Srl',
	'Paradiso',
	'Parrafo Aparte',
	'Patagonia Sur Libros',
	'Patria Grande',
	'Patris, Editorial',
	'Paulinas',
	'Payné',
	'Penguin Randon House',
	'Peniel',
	'Pequeña Hoja Editor',
	'Pequeño Editor',
	'Photo Design, Ediciones',
	'Pictus S.R.L.',
	'Pistarelli Alejandro Jorge',
	'Pitanguá',
	'Pixel Editora',
	'Placeres Perfectos',
	'Planta Editora',
	'Platense, Editorial',
	'Polemos',
	'Portaculturas',
	'Postales Japonesas',
	'Ppc Editorial',
	'Praia',
	'Praxis Juridica',
	'Prentice Hall - Pearson Education',
	'Producciones Publiexpress Sa',
	'Proeme',
	'Prohistoria Ediciones',
	'Prometeo',
	'Prosa Y Poesia - Amerian Srl',
	'Proyecto 451',
	'Puerco espín',
	'Puerto Creativo',
	'Puerto De Palos',
	'Purmamarka Ediciones',
	'Qellqasqa',
	'Quintana Liliana Ines',
	'Quiosquito Virtual',
	'Quipu, Editorial',
	'Quondam',
	'RBA',
	'Rama Negra',
	'Raul Manuel Oroza',
	'Raíz de dos',
	'Re Vista Vocacional',
	'Reflexiones Para El Alma',
	'Reijenstein Pablo Hugo',
	'Remitente Patagonia',
	'Restaurant De La Mente',
	'Ricordi',
	'RiderChail Editions',
	'Rodriguez Leonardo Daniel',
	'Rubinzal',
	'Rubinzal Culzoni Editores',
	'Rudi Sazunic',
	'Ruedamares',
	'Ruiz Irma Liliana',
	'Ruy Diaz, Editorial',
	'RyR',
	'Ríos de Tinta',
	'San Pablo',
	'Sandi Horacio Gustavo',
	'Santa Fe, Libreria',
	'Santiago Arcos Editor',
	'Santillana',
	'Serendipidad',
	'Señora Independencia',
	'Señora Porteña',
	'Siglo XXI Argentina',
	'Sigmar',
	'Sima Editora',
	'Siteca S.A.',
	'Six Ediciones Srl',
	'Sociedad Biblica Argentina',
	'Stadium',
	'Stella, Editorial (La Crujia)',
	'Stratford Book Services SA',
	'Suimanga',
	'Summamas',
	'Suárez',
	'Südpol',
	'Tafi Ediciones',
	'Tahiel Ediciones',
	'Talita Kum Ediciones',
	'Talwin',
	'Temas Grupo Editorial',
	'Terra-Basilico',
	'Testimonio De Autores Catolicos Escogidos',
	'The Bhaktivedanta Book Trust Argentina',
	'The Bookcellar',
	'Ticargas Int. Logistics Services Sa',
	'Tiempo Sur Ediciones',
	'Time & Money Netword Editions',
	'Tinta Libre Ediciones',
	'Tinta Limón',
	'Topia',
	'Treintayseis',
	'Trenkehue, Editorial',
	'Tres Haches',
	'Tres Sol Editorial',
	'Tribuna Epsilon',
	'Tusquets Editores',
	'Técnicas RT',
	'U.N.R., Editora',
	'UNIPE: Editorial Universitaria',
	'UNM Editora',
	'Ugerman, Editor',
	'Ulpiano (Textos Jurídicos)',
	'Un. Juan Agustin Maza',
	'Un. Nac. De Gral Sarmiento',
	'UniRío editora',
	'Unishop S.A.',
	'Universidad Nacional De Las Artes',
	'Universidad Nacional de Río Negro',
	'Universidad Nacional de Santiago Del Estero',
	'Universidad Nacional de la Matanza',
	'Universidad Nacional de la Patagonia Austral',
	'Universidad Pascal',
	'Unión Obrera Gráfica Cordobesa',
	'Unlpam',
	'Unsam Edita',
	'Ursino, Libreria',
	'Utopias',
	'V & R Editoras',
	'Vrtice',
	'Vzquez Mazzini Editores',
	'Vallarta Sa',
	'Valletta, Ediciones',
	'Vela al Viento Ediciones Patagonicas',
	'Verde Mente',
	'Vestales, Editorial',
	'Vi-Da Global',
	'Vicens Vives Argentina',
	'Viento de Fondo',
	'Vinciguerra',
	'Visor Enciclopedias Audiovisuales SA',
	'Voces',
	'Víctor Manuel Hanne Editor',
	'W Editores',
	'Waldhuter',
	'Wolkowicz Editores',
	'Ya Es Tiempo Ediciones',
	'Yaguarón Ediciones',
	'Zambrana Nicolas Horacio',
	'Zavalia',
	'Zeta Editores',
] as const;
